# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BM_UI.ui'
#
# Created: Mon Jan 16 10:33:55 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.ImFileName_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImFileName_label.sizePolicy().hasHeightForWidth())
        self.ImFileName_label.setSizePolicy(sizePolicy)
        self.ImFileName_label.setObjectName("ImFileName_label")
        self.horizontalLayout_3.addWidget(self.ImFileName_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.FullScreen_pushButton = QtGui.QPushButton(self.centralwidget)
        self.FullScreen_pushButton.setObjectName("FullScreen_pushButton")
        self.horizontalLayout_3.addWidget(self.FullScreen_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImBack_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImBack_pushButton.sizePolicy().hasHeightForWidth())
        self.ImBack_pushButton.setSizePolicy(sizePolicy)
        self.ImBack_pushButton.setObjectName("ImBack_pushButton")
        self.horizontalLayout_2.addWidget(self.ImBack_pushButton)
        self.Image_graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.Image_graphicsView.setObjectName("Image_graphicsView")
        self.horizontalLayout_2.addWidget(self.Image_graphicsView)
        self.ImForward_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImForward_pushButton.sizePolicy().hasHeightForWidth())
        self.ImForward_pushButton.setSizePolicy(sizePolicy)
        self.ImForward_pushButton.setObjectName("ImForward_pushButton")
        self.horizontalLayout_2.addWidget(self.ImForward_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.SeeMarks_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.SeeMarks_checkBox.setChecked(True)
        self.SeeMarks_checkBox.setObjectName("SeeMarks_checkBox")
        self.horizontalLayout.addWidget(self.SeeMarks_checkBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.EditMarks_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.EditMarks_checkBox.setChecked(False)
        self.EditMarks_checkBox.setObjectName("EditMarks_checkBox")
        self.horizontalLayout.addWidget(self.EditMarks_checkBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Bacillus_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.Bacillus_radioButton.setObjectName("Bacillus_radioButton")
        self.horizontalLayout.addWidget(self.Bacillus_radioButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.BacillusCluster_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.BacillusCluster_radioButton.setObjectName("BacillusCluster_radioButton")
        self.horizontalLayout.addWidget(self.BacillusCluster_radioButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.Undefined_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.Undefined_radioButton.setObjectName("Undefined_radioButton")
        self.horizontalLayout.addWidget(self.Undefined_radioButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.Delete_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.Delete_radioButton.setObjectName("Delete_radioButton")
        self.horizontalLayout.addWidget(self.Delete_radioButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.OpenFolder_action = QtGui.QAction(MainWindow)
        self.OpenFolder_action.setObjectName("OpenFolder_action")
        self.Close_action = QtGui.QAction(MainWindow)
        self.Close_action.setObjectName("Close_action")
        self.About_action = QtGui.QAction(MainWindow)
        self.About_action.setObjectName("About_action")
        self.AboutQt_action = QtGui.QAction(MainWindow)
        self.AboutQt_action.setObjectName("AboutQt_action")
        self.Login_action = QtGui.QAction(MainWindow)
        self.Login_action.setObjectName("Login_action")
        self.UserInfo_action = QtGui.QAction(MainWindow)
        self.UserInfo_action.setObjectName("UserInfo_action")
        self.ExportMarks_action = QtGui.QAction(MainWindow)
        self.ExportMarks_action.setObjectName("ExportMarks_action")
        self.Count_Bacillus_action = QtGui.QAction(MainWindow)
        self.Count_Bacillus_action.setObjectName("Count_Bacillus_action")
        self.menuFile.addAction(self.OpenFolder_action)
        self.menuFile.addAction(self.Close_action)
        self.menuHelp.addAction(self.About_action)
        self.menuHelp.addAction(self.AboutQt_action)
        self.menuTools.addAction(self.Login_action)
        self.menuTools.addAction(self.UserInfo_action)
        self.menuTools.addAction(self.ExportMarks_action)
        self.menuTools.addAction(self.Count_Bacillus_action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BacillusMarker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImFileName_label.setText(QtGui.QApplication.translate("MainWindow", "Bacillus image file name", None, QtGui.QApplication.UnicodeUTF8))
        self.FullScreen_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.ImBack_pushButton.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.ImForward_pushButton.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.SeeMarks_checkBox.setText(QtGui.QApplication.translate("MainWindow", "See Marks", None, QtGui.QApplication.UnicodeUTF8))
        self.EditMarks_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Edit Marks", None, QtGui.QApplication.UnicodeUTF8))
        self.Bacillus_radioButton.setText(QtGui.QApplication.translate("MainWindow", "Bacillus", None, QtGui.QApplication.UnicodeUTF8))
        self.BacillusCluster_radioButton.setText(QtGui.QApplication.translate("MainWindow", "Bacillus Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.Undefined_radioButton.setText(QtGui.QApplication.translate("MainWindow", "Undefined", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_radioButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenFolder_action.setText(QtGui.QApplication.translate("MainWindow", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_action.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.About_action.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.AboutQt_action.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.Login_action.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.UserInfo_action.setText(QtGui.QApplication.translate("MainWindow", "User Info", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportMarks_action.setText(QtGui.QApplication.translate("MainWindow", "Export Marks as BMP", None, QtGui.QApplication.UnicodeUTF8))
        self.Count_Bacillus_action.setText(QtGui.QApplication.translate("MainWindow", "Count Bacillus in Tail Region", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

